apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: guestbook
  namespace: kargo-helm
spec:
  subscriptions:
  - image:
      repoURL: ghcr.io/iben12/guestbook
      imageSelectionStrategy: SemVer

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: guestbook-chart
  namespace: kargo-helm
spec:
  subscriptions:
  - chart:
      repoURL: oci://registry-1.docker.io/iben12/guestbook-chart
      discoveryLimit: 20
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: features
  namespace: kargo-helm
spec:
  subscriptions:
  - git:
      branch: main
      commitSelectionStrategy: NewestFromBranch
      discoveryLimit: 20
      repoURL: https://github.com/iben12/kargo-helm.git
      includePaths:
      - base/feature-flags.yaml
