apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kargo-helm
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  destinations:
  - name: '*'
    namespace: kargo-helm-*
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/iben12/kargo-helm.git
  - https://registry-1.docker.io/iben12
