apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-helm
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/iben12/kargo-helm.git
      revision: HEAD
      directories:
      - path: env/*
  template:
    metadata:
      name: kargo-helm-{{path.basename}}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-helm:{{path.basename}}
    spec:
      destination:
        namespace: kargo-helm-{{path.basename}}
        name: in-cluster
      project: kargo-helm
      sources:
        - repoURL: https://github.com/iben12/kargo-helm.git
          path: env/{{path.basename}}
          targetRevision: HEAD
          ref: values
        - chart: guestbook-chart
          repoURL: registry-1.docker.io/iben12
          targetRevision: ^0.1.0
          helm:
            passCredentials: true
            releaseName: guestbook
            valueFiles:
            - "$vaules/values.yaml"
            - "$vaules/feature-flags.yaml"
