apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-helm
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/iben12/kargo-helm.git
      revision: HEAD
      directories:
      - path: env/*
  template:
    metadata:
      name: kargo-helm-{{path.basename}}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-helm:{{path.basename}}
    spec:
      destination:
        namespace: kargo-helm-{{path.basename}}
        name: in-cluster
      project: kargo-helm
      source:
        chart: guestbook
        repoURL: ghcr.io/iben12/guestbook-chart
        targetRevision: 0.1.0
        helm:
          releaseName: guestbook
          valueFiles:
          - "/env/{{path.basename}}/values.yaml"
          - "/env/{{path.basename}}/feature-flags.yaml"
